[cluster]
master    ansible_host=192.168.2.44   new_hostname=master
worker1   ansible_host=192.168.2.11   new_hostname=worker1
worker2   ansible_host=192.168.2.22   new_hostname=worker2
worker3   ansible_host=192.168.2.33 new_hostname=worker3

[masters]
master

[workers]
worker1
worker2
worker3