---
- name: 1. Base Configuration (All Nodes)
  hosts: cluster
  become: yes
  tasks:
    - name: Install Essential Tools (Fixes K3s iptables error)
      apt:
        name: [python3-apt, iptables, curl]
        state: present
        update_cache: yes

    - name: Set Static IP on Ethernet (Using Netplan Profile)
      shell: |
        nmcli con mod "netplan-eth0" \
        ipv4.addresses "{{ new_ip }}/24" \
        ipv4.gateway "192.168.2.1" \
        ipv4.dns "8.8.8.8" \
        ipv4.method manual
      ignore_errors: yes 

    - name: Disable Swap
      shell: |
        dphys-swapfile swapoff
        dphys-swapfile uninstall
        update-rc.d dphys-swapfile remove
      ignore_errors: yes

    - name: Enable cgroups in cmdline.txt
      replace:
        path: /boot/firmware/cmdline.txt
        regexp: '^([\w\s~=./#%+-]*)$'
        replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      register: boot_config

    - name: MANDATORY REBOOT
      reboot:
        reboot_timeout: 300
